#pragma once

#include <Sonic/Message/MsgChangeGameSpeed.h>
#include <Sonic/Message/MsgChangeMotionInExternalControl.h>
#include <Sonic/Message/MsgCheckPermissionAttack.h>
#include <Sonic/Message/MsgDamage.h>
#include <Sonic/Message/MsgDamageSuccess.h>
#include <Sonic/Message/MsgDeactivate.h>
#include <Sonic/Message/MsgEndHangOn.h>
#include <Sonic/Message/MsgEndQuickStepSign.h>
#include <Sonic/Message/MsgExitedExternalControl.h>
#include <Sonic/Message/MsgExitedHangOn.h>
#include <Sonic/Message/MsgFinishExternalControl.h>
#include <Sonic/Message/MsgGetEnemyType.h>
#include <Sonic/Message/MsgGetItemType.h>
#include <Sonic/Message/MsgGetPlayerType.h>
#include <Sonic/Message/MsgHitEventCollision.h>
#include <Sonic/Message/MsgIsExternalControl.h>
#include <Sonic/Message/MsgIsReceiveDamage.h>
#include <Sonic/Message/MsgIsWall.h>
#include <Sonic/Message/MsgLeaveEventCollision.h>
#include <Sonic/Message/MsgMissionFinish.h>
#include <Sonic/Message/MsgNotifyInput.h>
#include <Sonic/Message/MsgNotifyObjectEvent.h>
#include <Sonic/Message/MsgNotifyShockWave.h>
#include <Sonic/Message/MsgReopenActivity.h>
#include <Sonic/Message/MsgRestartStage.h>
#include <Sonic/Message/MsgShakeCamera.h>
#include <Sonic/Message/MsgStageClear.h>
#include <Sonic/Message/MsgStartExternalControl.h>
#include <Sonic/Message/MsgStartFadeIn.h>
#include <Sonic/Message/MsgStartFadeOut.h>
#include <Sonic/Message/MsgStartHangOn.h>
#include <Sonic/Message/MsgStartOutOfControl.h>
#include <Sonic/Message/MsgStopActivity.h>
#include <Sonic/Message/MsgTakeObject.h>

#include <Sonic/CCharacterProxy.h>
#include <Sonic/CGlitterPlayer.h>
#include <Sonic/CShapeCollision.h>
